{% set name = "pyserini" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyserini-{{ version }}.tar.gz
  sha256: 9a8cf07fc8bdcf50942e42ed69a9a569da60709e14e1aabb5461464a54116459

build:
  skip: true  # [py<=310 or py>311]
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - datasets
    - fastmcp >=2.10.4
    - matplotlib-base
    - fastapi >=0.70.0
    - mcp >=1.9.4
    - uvicorn >=0.13.0
    - faiss >1.7.0
    - flask >3.0
    - pytorch >=2.4.0
    - requests
    - python
    - cython >=0.29.21
    - cython-blis <1
    - numpy >=1.18.1
    - pandas >=1.4.0
    - pyjnius >=1.6.0
    - scikit-learn >=0.22.1
    - scipy >=1.4.1
    - tqdm
    - transformers >=4.6.0
    - sentencepiece >=0.2
    - nmslib >=2.0.6
    - onnxruntime >=1.8.1
    - lightgbm >=3.3.2
    - spacy >=3.2.1
    - pyyaml
    - openai >=1.0.0
    - tiktoken >=0.4.0
    - pyarrow >=15.0.0
    - pillow >=10.2.0
    - pybind11 >=2.11.0

test:
  imports:
    - pyserini
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/castorini/pyserini
  summary: A Python toolkit for reproducible information retrieval research with sparse and dense representations
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
