{% set name = "pyserini" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyserini-{{ version }}.tar.gz
  sha256: ecaa7b165690b3daa659b16e52ef5edabd29c903129dd132d03857dd5aeee650

build:
  skip: true  # [py<=310 or py>311]
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - datasets
    - fastmcp >=2.14
    - matplotlib-base
    - fastapi >=0.124
    - mcp >=1.9.4
    - uvicorn >=0.38
    - faiss >1.7.0
    - flask
    - pytorch >=2.9
    - requests
    - python
    - cython
    - cython-blis <1
    - numpy >=2
    - pandas
    - pyjnius >=1.7.0
    - scikit-learn
    - scipy
    - tqdm
    - transformers >=4.57
    - sentencepiece >=0.2
    - nmslib >=2.0.6
    - onnxruntime >=1.23
    - lightgbm >=3.3.2
    - spacy >=3.2.1
    - pyyaml
    - openai >=2.12.0
    - tiktoken >=0.12
    - pyarrow >=15.0.0
    - pillow >=12
    - pybind11 >=2.11.0

test:
  imports:
    - pyserini
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/castorini/pyserini
  summary: A Python toolkit for reproducible information retrieval research with sparse and dense representations
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
